import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BellRing, Flame, LogIn } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function Alerts() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const overview = trpc.fireguard.overview.useQuery(); const mark = trpc.fireguard.markAlertRead.useMutation({ onSuccess: () => { utils.fireguard.overview.invalidate(); toast.success("Alerta marcado como lido."); }, onError: error => toast.error(error.message) });
  return <main className="min-h-screen bg-[#f7f7ef] p-5 text-[#173b35] lg:p-8"><div className="mx-auto max-w-4xl"><div className="mb-9 flex items-center justify-between"><Link href="/dashboard" className="flex items-center gap-2 text-sm font-bold text-[#416f5d]"><ArrowLeft className="h-4 w-4" />Painel operacional</Link><Link href="/" className="flex items-center gap-2 text-sm font-extrabold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#1c4a3d] text-[#d7e981]"><Flame className="h-4 w-4" /></span>FireGuard</Link></div><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#a36931]">Sinais e atualizações</p><h1 className="mt-2 font-serif text-4xl">Central de alertas</h1><p className="mt-2 text-sm text-[#71877e]">O estado de leitura é persistido para sua sessão operacional.</p>{!user ? <Card className="mt-7 rounded-2xl border-[#dbe6d8] bg-[#fcfdf9] shadow-none"><CardContent className="p-6"><p className="font-semibold">Entre para registrar leituras de alerta.</p><Button onClick={() => startLogin()} className="mt-4 rounded-xl bg-[#1c4a3d]"><LogIn className="mr-2 h-4 w-4" />Entrar ou cadastrar-se</Button></CardContent></Card> : <div className="mt-7 space-y-3">{overview.data?.alerts.map(alert => <button key={alert.id} onClick={() => !alert.isRead && mark.mutate({ id: alert.id })} className={`flex w-full gap-4 rounded-2xl border p-5 text-left ${alert.isRead ? "border-[#dbe6d8] bg-[#fcfdf9]" : "border-[#e7c7ae] bg-[#fffaf3]"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${alert.severity === "critical" ? "bg-[#f8e3df] text-[#c04333]" : "bg-[#e8f0df] text-[#547b57]"}`}><BellRing className="h-5 w-5" /></span><span className="min-w-0"><span className="flex items-center gap-2"><strong className="text-sm">{alert.title}</strong>{!alert.isRead ? <i className="h-2 w-2 rounded-full bg-[#cd5037]" /> : null}</span><span className="mt-1 block text-sm leading-6 text-[#688178]">{alert.message}</span><span className="mt-2 block font-mono text-[9px] uppercase tracking-wider text-[#8b9d95]">{alert.isSimulated ? "Dado simulado no MVP · " : ""}{new Date(alert.createdAt).toLocaleString("pt-BR")}</span></span></button>)}</div>}</div></main>;
}
