import { useState } from "react";
import { Link } from "wouter";
import { ArrowRight, BarChart3, Bell, Check, ChevronDown, ClipboardCheck, FileText, Flame, Menu, QrCode, ShieldCheck, Smartphone, Users, X, Wrench, AlertTriangle, CalendarClock } from "lucide-react";
import { Button } from "@/components/ui/button";

const solutionCards = [
  { icon: Wrench, title: "Equipamentos", text: "Mantenha extintores, hidrantes e ativos organizados por unidade e situação." },
  { icon: ClipboardCheck, title: "Inspeções", text: "Conduza checklists com clareza e acompanhe o que ainda precisa de atenção." },
  { icon: AlertTriangle, title: "Ocorrências", text: "Registre ocorrências, responsáveis e próximos passos em um único fluxo." },
  { icon: FileText, title: "Documentos", text: "Centralize arquivos operacionais para encontrar a informação quando precisar." },
  { icon: BarChart3, title: "Relatórios", text: "Transforme o histórico da operação em visibilidade para decisões melhores." },
  { icon: Users, title: "Equipes", text: "Organize responsáveis, permissões e acompanhamento por unidade." },
  { icon: Bell, title: "Alertas", text: "Receba sinais sobre pendências, riscos e vencimentos próximos." },
  { icon: QrCode, title: "QR Code", text: "Consulte o histórico de cada equipamento diretamente no local." },
];

const problems = ["Equipamentos sem acompanhamento", "Inspeções esquecidas", "Documentos espalhados", "Vencimentos não monitorados", "Falta de histórico", "Dificuldade para acompanhar riscos"];
const faqs = [
  ["O que é o FireGuard?", "É uma plataforma SaaS para organizar a gestão de segurança contra incêndios, reunindo equipamentos, inspeções, documentos, riscos e ocorrências."],
  ["Para quem é o FireGuard?", "Para empresas e equipes que precisam centralizar sua operação de segurança e acompanhar responsabilidades por unidade."],
  ["Posso cadastrar equipamentos?", "A experiência do MVP já possui uma base operacional simulada e foi estruturada para receber cadastros reais de equipamentos."],
  ["Como funcionam as inspeções?", "O fluxo foi desenhado para checklists, registros e acompanhamento de pendências. Integrações específicas podem ser configuradas conforme a operação."],
  ["Como funciona o QR Code?", "Cada equipamento pode ter um QR Code para abrir sua identificação, situação, histórico e inspeções quando essa configuração estiver ativa."],
  ["Existe aplicativo?", "Neste momento, o FireGuard é uma aplicação web responsiva, acessível pelo navegador em computador e celular."],
  ["Como funciona a segurança dos dados?", "O projeto usa sessão protegida, hash de senha no cadastro local e variáveis de ambiente para configurações sensíveis."],
];
const plans: Array<[string, string, string[]]> = [["STARTER", "Para pequenas empresas.", ["Base operacional", "Inspeções e pendências", "Acesso web"]], ["PROFISSIONAL", "Para empresas em crescimento.", ["Gestão por unidade", "Relatórios e alertas", "Histórico centralizado"]], ["ENTERPRISE", "Para operações maiores.", ["Fluxos personalizados", "Governança de equipes", "Fale conosco"]]];

function Brand() { return <Link href="/" className="flex items-center gap-3 text-[#12151a]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#ff5a24] text-white shadow-lg shadow-[#ff5a24]/20"><Flame className="h-5 w-5 fill-current" /></span><span><strong className="block text-lg font-black tracking-tight">FireGuard</strong><small className="block text-[9px] font-bold uppercase tracking-[.24em] text-[#77808b]">Safety operations</small></span></Link>; }

function DashboardPreview() { return <div className="relative mx-auto w-full max-w-[560px] lg:ml-auto"><div className="absolute -right-5 -top-5 h-32 w-32 rounded-full bg-[#ff5a24]/15 blur-2xl" /><div className="relative rounded-[2rem] border border-white/10 bg-[#20252b] p-3 shadow-2xl shadow-black/30 sm:p-5"><div className="rounded-[1.4rem] bg-[#f8f9fa] p-4 text-[#171a1e] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#87909a]">Visão geral</p><h3 className="mt-1 text-lg font-black">Centro de segurança</h3></div><span className="rounded-full bg-[#fff0ea] px-3 py-1 text-[10px] font-bold text-[#d8481c]">DEMONSTRAÇÃO</span></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Equipamentos","128"],["Inspeções","12"],["Ocorrências","03"],["Conformidade","92%"]].map(([label,value]) => <div key={label} className="rounded-2xl border border-[#e6e9ec] bg-white p-3"><p className="text-[10px] text-[#7c8792]">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-[1.4fr_.8fr]"><div className="rounded-2xl bg-[#f1f4f6] p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold">Pendências por semana</p><BarChart3 className="h-4 w-4 text-[#ff5a24]" /></div><div className="mt-5 flex h-24 items-end gap-2">{[35,58,43,78,52,66,88].map((height,index) => <span key={index} className={`flex-1 rounded-t-md ${index === 6 ? "bg-[#ff5a24]" : "bg-[#cbd3da]"}`} style={{ height: `${height}%` }} />)}</div></div><div className="rounded-2xl bg-[#1f282d] p-4 text-white"><p className="text-[10px] uppercase tracking-[.15em] text-[#aeb9be]">Próximo vencimento</p><p className="mt-5 text-3xl font-black">07</p><p className="mt-1 text-xs text-[#aeb9be]">itens neste mês</p><div className="mt-4 flex items-center gap-2 text-xs text-[#ffb39b]"><CalendarClock className="h-4 w-4" />Acompanhar</div></div></div></div></div></div>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <main className="min-h-screen bg-[#f7f8f9] text-[#15191e]">
    <header className="sticky top-0 z-30 border-b border-[#e9ecef]/80 bg-[#f7f8f9]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Brand /><nav className="hidden items-center gap-7 text-sm font-bold text-[#5f6974] lg:flex"><a href="#solucao" className="transition-colors hover:text-[#ff5a24]">Funcionalidades</a><a href="#como-funciona" className="transition-colors hover:text-[#ff5a24]">Como funciona</a><a href="#planos" className="transition-colors hover:text-[#ff5a24]">Planos</a><a href="#faq" className="transition-colors hover:text-[#ff5a24]">FAQ</a></nav><div className="hidden items-center gap-3 sm:flex"><Link href="/login" className="px-3 text-sm font-bold text-[#4d5864] hover:text-[#ff5a24]">Entrar</Link><Link href="/register"><Button className="rounded-xl bg-[#ff5a24] font-bold text-white hover:bg-[#e84d1b]">Começar agora<ArrowRight className="ml-2 h-4 w-4" /></Button></Link></div><button aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} className="rounded-xl border border-[#dce1e5] p-2 lg:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>{menuOpen && <div className="border-t border-[#e9ecef] bg-white px-5 py-4 lg:hidden"><div className="grid gap-3 text-sm font-bold"><a href="#solucao" onClick={() => setMenuOpen(false)}>Funcionalidades</a><a href="#como-funciona" onClick={() => setMenuOpen(false)}>Como funciona</a><a href="#planos" onClick={() => setMenuOpen(false)}>Planos</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a><Link href="/login">Entrar</Link><Link href="/register" className="text-[#ff5a24]">Começar agora</Link></div></div>}</header>
    <section className="overflow-hidden bg-[#171b20] text-white"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-16 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8 lg:py-24"><div className="enter"><div className="mb-6 flex w-fit items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#ffb39b]"><span className="h-1.5 w-1.5 rounded-full bg-[#ff5a24]" />Gestão inteligente de segurança</div><h1 className="max-w-2xl text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Sua segurança contra incêndios, <span className="text-[#ff7040]">sob controle.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-[#b9c1c8] sm:text-lg">Gerencie inspeções, equipamentos, documentos e riscos em uma única plataforma.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/register"><Button size="lg" className="h-13 rounded-xl bg-[#ff5a24] px-6 font-black text-white hover:bg-[#e84d1b]">Começar agora<ArrowRight className="ml-2 h-5 w-5" /></Button></Link><a href="#demo"><Button size="lg" variant="outline" className="h-13 rounded-xl border-white/20 bg-white/5 px-6 font-bold text-white hover:bg-white/10 hover:text-white">Ver demonstração</Button></a></div><div className="mt-12 grid grid-cols-3 gap-4 border-t border-white/10 pt-6 text-xs text-[#aeb8c0]"><div><p className="text-xl font-black text-white">01</p><p className="mt-1">operação centralizada</p></div><div><p className="text-xl font-black text-white">24/7</p><p className="mt-1">visibilidade contínua</p></div><div><p className="text-xl font-black text-white">100%</p><p className="mt-1">web e responsivo</p></div></div></div><div id="demo"><DashboardPreview /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-[#ff5a24]">O problema</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-5xl">A segurança não pode depender de planilhas espalhadas.</h2><p className="mt-5 text-lg leading-8 text-[#6b7580]">Quando a operação cresce, acompanhar ativos, responsáveis e prazos manualmente cria ruído e dificulta a priorização.</p></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{problems.map((problem,index) => <div key={problem} className="flex items-center gap-4 rounded-2xl border border-[#e5e8eb] bg-white p-5 shadow-sm"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#fff0ea] font-mono text-xs font-bold text-[#ff5a24]">0{index+1}</span><span className="text-sm font-bold text-[#46515c]">{problem}</span></div>)}</div></section>
    <section id="solucao" className="bg-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-[#ff5a24]">A solução FireGuard</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-5xl">Tudo o que você precisa em um só lugar.</h2></div><p className="max-w-md text-sm leading-7 text-[#6b7580]">Uma base organizada para transformar tarefas dispersas em uma operação acompanhável.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{solutionCards.map(card => <article key={card.title} className="group rounded-3xl border border-[#e5e8eb] bg-[#fbfcfd] p-6 transition-all duration-200 hover:-translate-y-1 hover:border-[#ffb39b] hover:shadow-xl hover:shadow-[#ff5a24]/10"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#fff0ea] text-[#ff5a24] transition-colors group-hover:bg-[#ff5a24] group-hover:text-white"><card.icon className="h-5 w-5" /></span><h3 className="mt-6 font-black">{card.title}</h3><p className="mt-3 text-sm leading-6 text-[#737e89]">{card.text}</p></article>)}</div></div></section>
    <section id="como-funciona" className="bg-[#f1f3f5]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="text-center"><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-[#ff5a24]">Como funciona</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-5xl">Do problema à solução em 3 passos.</h2></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{[["01","Cadastre","Cadastre equipamentos, unidades e responsáveis."],["02","Inspecione","Realize inspeções e checklists diretamente pelo sistema."],["03","Acompanhe","Monitore riscos, pendências, vencimentos e indicadores."]].map(([number,title,text]) => <article key={number} className="rounded-3xl bg-white p-7 shadow-sm"><span className="font-mono text-sm font-bold text-[#ff5a24]">{number}</span><h3 className="mt-10 text-2xl font-black">{title}</h3><p className="mt-3 leading-7 text-[#707b86]">{text}</p><div className="mt-8 h-1 w-16 rounded-full bg-[#ff5a24]" /></article>)}</div></div></section>
    <section className="bg-[#171b20] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1fr_.9fr] lg:items-center lg:px-8 lg:py-28"><div><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-[#ff8a67]">QR Code operacional</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em] sm:text-5xl">Tenha o histórico de cada equipamento na palma da mão.</h2><p className="mt-5 max-w-xl leading-8 text-[#aeb8c0]">Cada ativo pode ter uma identificação própria para consultar informações, histórico, inspeções e situação no local. O fluxo também pode permitir novos registros quando estiver configurado.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Identificar equipamento","Consultar histórico","Ver inspeções","Consultar situação"].map(item => <div key={item} className="flex items-center gap-3 text-sm font-bold text-[#d9dfe3]"><Check className="h-4 w-4 text-[#ff7040]" />{item}</div>)}</div></div><div className="mx-auto grid h-64 w-64 place-items-center rounded-3xl bg-white p-6 shadow-2xl shadow-black/30"><div className="grid h-full w-full place-items-center rounded-xl border-8 border-[#171b20] bg-[repeating-linear-gradient(45deg,#171b20_0,#171b20_5px,#fff_5px,#fff_10px)]"><div className="rounded-lg bg-white p-3"><QrCode className="h-20 w-20 text-[#171b20]" /></div></div></div></div></section>
    <section id="planos" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="text-center"><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-[#ff5a24]">Planos</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em]">Escolha o momento da sua operação.</h2><p className="mx-auto mt-4 max-w-xl text-[#6b7580]">Estruturas pensadas para diferentes níveis de organização. Valores disponíveis em breve.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{plans.map(([name,description,items],index) => <article key={name} className={`rounded-3xl border p-7 ${index === 1 ? "border-[#ff5a24] bg-[#fff8f5] shadow-xl shadow-[#ff5a24]/10" : "border-[#e5e8eb] bg-white"}`}><div className="flex items-center justify-between"><h3 className="font-mono text-sm font-bold tracking-[.15em]">{name}</h3>{index === 1 && <span className="rounded-full bg-[#ff5a24] px-3 py-1 text-[10px] font-bold text-white">EM DESTAQUE</span>}</div><p className="mt-5 text-sm text-[#6b7580]">{description}</p><p className="mt-8 text-2xl font-black">Em breve</p><div className="mt-6 space-y-3">{items.map(item => <div key={item} className="flex items-center gap-2 text-sm text-[#58636e]"><Check className="h-4 w-4 text-[#1caf8a]" />{item}</div>)}</div><Button variant="outline" className="mt-8 w-full rounded-xl border-[#dce1e5] font-bold">Fale conosco</Button></article>)}</div></section>
    <section id="faq" className="bg-white"><div className="mx-auto max-w-4xl px-5 py-20 lg:px-8 lg:py-28"><div className="text-center"><p className="font-mono text-xs font-bold uppercase tracking-[.2em] text-[#ff5a24]">FAQ</p><h2 className="mt-4 text-4xl font-black tracking-[-.045em]">Perguntas frequentes.</h2></div><div className="mt-12 divide-y divide-[#e5e8eb] border-y border-[#e5e8eb]">{faqs.map(([question,answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-[#252b31]"><span>{question}</span><ChevronDown className="h-5 w-5 text-[#ff5a24] transition-transform group-open:rotate-180" /></summary><p className="max-w-3xl pt-3 text-sm leading-7 text-[#6b7580]">{answer}</p></details>)}</div></div></section>
    <section className="px-5 py-16 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 rounded-[2rem] bg-[#ff5a24] px-7 py-12 text-white sm:px-12 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-4xl font-black tracking-[-.045em]">Proteja sua operação com o FireGuard.</h2><p className="mt-3 max-w-xl text-[#ffe1d6]">Centralize sua gestão de segurança contra incêndios em uma única plataforma.</p></div><Link href="/register"><Button size="lg" className="rounded-xl bg-white font-black text-[#d8491c] hover:bg-[#fff5f1]">Começar agora<ArrowRight className="ml-2 h-5 w-5" /></Button></Link></div></section>
    <footer className="border-t border-[#e5e8eb] bg-white px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 sm:flex-row sm:items-center"><Brand /><p className="text-sm text-[#7a858f]">Gestão inteligente de segurança contra incêndios.</p></div></footer>
  </main>;
}
