import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { ArrowRight, Flame, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function Onboarding() {
  const { user, loading } = useAuth();
  return <main className="grid min-h-screen place-items-center overflow-hidden bg-[#10332d] p-5 text-[#f6f5e9]"><div className="pointer-events-none absolute inset-0 opacity-30" style={{ backgroundImage: "linear-gradient(rgba(202,226,172,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(202,226,172,.12) 1px,transparent 1px)", backgroundSize: "44px 44px" }} /><section className="relative z-10 w-full max-w-3xl rounded-[2rem] border border-white/10 bg-[#174036] p-7 shadow-2xl sm:p-11"><Link href="/" className="flex items-center gap-2 text-sm font-extrabold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#b7d76b] text-[#173b35]"><Flame className="h-4 w-4" /></span>FireGuard</Link><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_.72fr]"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.17em] text-[#cce47d]">Primeiro acesso</p><h1 className="mt-3 font-serif text-4xl leading-tight sm:text-5xl">Comece a proteger o que importa.</h1><p className="mt-4 max-w-md text-sm leading-6 text-[#c7d8cf]">Conclua seu cadastro para registrar denúncias, acompanhar ocorrências e receber atualizações do FireGuard.</p>{loading ? <p className="mt-8 text-sm text-[#c7d8cf]">Verificando seu acesso…</p> : user ? <Link href="/profile"><Button className="mt-8 rounded-xl bg-[#b7d76b] font-bold text-[#173b35] hover:bg-[#d5e88e]">Continuar para meu perfil <ArrowRight className="ml-2 h-4 w-4" /></Button></Link> : <Button type="button" onClick={startLogin} className="mt-8 rounded-xl bg-[#b7d76b] font-bold text-[#173b35] hover:bg-[#d5e88e]">Concluir cadastro e criar conta <ArrowRight className="ml-2 h-4 w-4" /></Button>}</div><div className="rounded-2xl border border-white/10 bg-black/10 p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-[#d7e981]"><ShieldCheck className="h-5 w-5" /></span><p className="mt-5 font-semibold">Seu acesso em três passos</p><div className="mt-5 space-y-4">{["Valide sua identidade com o provedor de acesso.", "Seu perfil FireGuard é criado com o papel Usuário.", "Edite seus dados e comece a participar."].map((item, index) => <div key={item} className="flex gap-3 text-sm leading-5 text-[#c5d8ce]"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#cce47d] text-[10px] font-bold text-[#173b35]">{index + 1}</span>{item}</div>)}</div><p className="mt-6 border-t border-white/10 pt-4 text-[11px] leading-5 text-[#afc6ba]">O papel pode ser alterado posteriormente por um Admin para Monitor ou Admin.</p></div></div></section></main>;
}
